name: glpi_dart
description: glpi_dart is a dart library to interact with the GLPI's REST API.
version: 0.0.1
homepage: https://github.com/shalien/glpi_dart
repository: https://github.com/shalien/glpi_dart
issue_tracker: https://github.com/shalien/glpi_dart/issues


environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: {http: ^0.13.4}

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dotenv: ^3.0.0
