name: glpi_dart
description:  >- 
  This library is a wrapper around the GLPI API, it provides a simple way to access he API. 
  It is based on the Dart http library so it can be used ont dartvm and dartweb. 
version: 0.1.6
homepage: https://github.com/shalien/glpi_dart
repository: https://github.com/shalien/glpi_dart
issue_tracker: https://github.com/shalien/glpi_dart/issues


environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: {http: ^0.13.4}

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dotenv: ^3.0.0
  dart_code_metrics: ^4.13.0

false_secrets:
  - /example/lib/*.dart
  - /test/*.dart